#!/bin/bash
function crt
{
    user="$(whoami)";
    host=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | awk -F":" '{print $2}');
    PWD="$(pwd)"

    if [[ $# == 1 ]]; then
        suffix="/$1"
        #statements
    else
        suffix=""
    fi

    echo ${user}@${host}:${PWD}${suffix}
}
